name: demo-github-actions
on: 
  push:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Write a multi-line message
          run: |
            echo "This demo file shows a"
            echo "very basic and easy-to-understand workflow."


